---

services:
  debezium-connect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debezium-connect-test
    platform: linux/amd64
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=localhost:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses